config/routes.rb
Rails.application.routes.draw do
  resources :nearest_stations
  resources :properties
  root 'properties#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nearest_station.rb
class NearestStation < ApplicationRecord
	belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
	validates :name, presence: true
	validates :rent, presence: true
	validates :building_age, presence: true
	validates :address, presence: true
	validates :remark, presence: true

	has_many :nearest_stations
	accepts_nested_attributes_for :nearest_stations, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nearest_stations_controller.rb
class NearestStationsController < ApplicationController
  before_action :set_nearest_station, only: %i[ show edit update destroy ]

  def index
    @nearest_stations = NearestStation.all
  end

  def show
  end

  def new
    @nearest_station = NearestStation.new
  end

  def edit
  end

  def create
    @nearest_station = NearestStation.new(nearest_station_params)

    respond_to do |format|
      if @nearest_station.save
        format.html { redirect_to @nearest_station, notice: "Nearest station was successfully created." }
        format.json { render :show, status: :created, location: @nearest_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nearest_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @nearest_station.update(nearest_station_params)
        format.html { redirect_to @nearest_station, notice: "Nearest station was successfully updated." }
        format.json { render :show, status: :ok, location: @nearest_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nearest_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @nearest_station.destroy
    respond_to do |format|
      format.html { redirect_to nearest_stations_url, notice: "Nearest station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nearest_station
      @nearest_station = NearestStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nearest_station_params
      params.require(:nearest_station).permit(:name_of_railway, :station_name, :how_many_minutes_walk)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = Property.new
    @property.nearest_stations.build
  end

  def edit
    @property.nearest_stations.build
  end

  def create
    @property = Property.new(property_params)
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :rent, :building_age, :address, :remark,
      nearest_stations_attributes: [:id, :name_of_railway, :station_name, :how_many_minutes_walk])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nearest_stations_helper.rb
module NearestStationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nearest_stations/_form.html.erb
<%= form_with(model: nearest_station, local: true) do |form| %>
  <% if nearest_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nearest_station.errors.count, "error") %> prohibited this nearest_station from being saved:</h2>

      <ul>
      <% nearest_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_of_railway %>
    <%= form.text_field :name_of_railway %>
  </div>

  <div class="field">
    <%= form.label :station_name %>
    <%= form.text_field :station_name %>
  </div>

  <div class="field">
    <%= form.label :how_many_minutes_walk %>
    <%= form.text_field :how_many_minutes_walk %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nearest_stations/edit.html.erb
<h1>Editing Nearest Station</h1>

<%= render 'form', nearest_station: @nearest_station %>

<%= link_to 'Show', @nearest_station %> |
<%= link_to 'Back', nearest_stations_path %>

app/views/nearest_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nearest Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name of railway</th>
      <th>Station name</th>
      <th>How many minutes walk</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nearest_stations.each do |nearest_station| %>
      <tr>
        <td><%= nearest_station.name_of_railway %></td>
        <td><%= nearest_station.station_name %></td>
        <td><%= nearest_station.how_many_minutes_walk %></td>
        <td><%= link_to 'Show', nearest_station %></td>
        <td><%= link_to 'Edit', edit_nearest_station_path(nearest_station) %></td>
        <td><%= link_to 'Destroy', nearest_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nearest Station', new_nearest_station_path %>

app/views/nearest_stations/new.html.erb
<h1>New Nearest Station</h1>

<%= render 'form', nearest_station: @nearest_station %>

<%= link_to 'Back', nearest_stations_path %>

app/views/nearest_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of railway:</strong>
  <%= @nearest_station.name_of_railway %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @nearest_station.station_name %>
</p>

<p>
  <strong>How many minutes walk:</strong>
  <%= @nearest_station.how_many_minutes_walk %>
</p>

<%= link_to 'Edit', edit_nearest_station_path(@nearest_station) %> |
<%= link_to 'Back', nearest_stations_path %>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.text_field :rent %>
  </div>

  <div class="field">
    <%= form.label :building_age %>
    <%= form.text_field :building_age %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_area :remark %>
  </div>

<hr />
<% if action_name == 'new'%>

  <%2.times do |dis| %>

    <h1>Name of railway line <%= dis + 1 %></h1>

    <%= form.fields_for :nearest_stations do |y| %>

      <div class="field">
        <%= y.label :name_of_railway %>
        <%= y.text_field :name_of_railway %>
      </div>

      <div class="field">
        <%= y.label :station_name %>
        <%= y.text_field :station_name %>
      </div>

      <div class="field">
        <%= y.label :how_many_minutes_walk %>
        <%= y.text_field :how_many_minutes_walk %> min / mins
      </div>

    <% end %>
  <% end %>
<% end %>

<% if action_name == 'edit'%>

  <% dis = 0 %>
  <%= form.fields_for :nearest_stations do |y| %>
  
    <% dis += 1 %>
    <h1>Name of railway line <%= dis %></h1>
    <div class="field">
      <%= y.label :name_of_railway %>
      <%= y.text_field :name_of_railway %>
    </div>

    <div class="field">
      <%= y.label :station_name %>
      <%= y.text_field :station_name %>
    </div>

    <div class="field">
      <%= y.label :how_many_minutes_walk %>
      <%= y.text_field :how_many_minutes_walk %> min / mins
    </div>

  <% end %>
<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Protery List</h1>

<%= link_to 'New Property', new_property_path %>

<table style="margin-top: 50px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rent</th>
      <th>Building age</th>
      <th>Address</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.rent %></td>
        <td><%= property.building_age %></td>
        <td><%= property.address %></td>
        <td><%= property.remark %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building_age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @property.remark %>
</p>

<hr />

<% i = 0 %>
<% @property.nearest_stations.each do |x| %>
<% if x.name_of_railway != "" && x.station_name != "" && x.how_many_minutes_walk != "" %>
  <h1> Nearest station<%= i+1 %>
  <p>
    <strong>Name of railway:</strong>
    <%= x.name_of_railway %>
  </p>

  <p>
    <strong>Station name:</strong>
    <%= x.station_name %>
  </p>

  <p>
    <strong>How many minutes walk:</strong>
    <%= x.how_many_minutes_walk %>
  </p>
  <% i += 1 %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>